version: "3.1"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    volumes:
      - /Users/duyeong/Projects/yeondutalk/db/mysql:/var/lib/mysql
